parallel-jobs = 1

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "Anddea patches"
version = "auto"
arch = "both"
build-mode = "both"
included-patches = "'Hide Shorts dimming' 'Theme'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true"

[Photos]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
included-patches = "'Enable DCIM folders backup control'"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"
