parallel-jobs = 1

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "Anddea patches"
version = "auto"
build-mode = "both"
included-patches = "'Hide Shorts dimming' 'Theme'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true"

[Photos]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
arch = "arm64-v8a"
patches-version = "v5.50.3-dev.3"
included-patches = "'Enable DCIM folders backup control'"
